version: '3.6'

services:
  db:
    image: mysql:8.0.29
    volumes:
      - db-mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PWD
      MYSQL_DATABASE: app
    container_name: db_c

  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      restart: always
    container_name: phpmyadmin_c

  server:
    image: node:16.16.0-alpine
    volumes:
      - ./backend:/usr/local/backend
    working_dir: /usr/local/backend
    env_file: .env
    ports:
      - '127.0.0.1:3000:3000'
    command: npm run dev
    container_name: server_c
    depends_on:
      - db

volumes:
  mongo-data: {}
  db-mysql: {}

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
  #     - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
  #   ports:
  #     - '5050:80'
  #   restart: always
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   container_name: pga_c

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./SampleCollections:/usr/local/sampleCollections
  #     - mongo-data:/data/db
  #   working_dir: /usr/local/sampleCollections
  #   container_name: mongo_c

  # client:
  #   image: node:alpine
  #   volumes:
  #     - ./client:/usr/local/server
  #   working_dir: /usr/local/server
  #   environment:
  #     - REACT_API_URL=http://server:3000
  #   ports:
  #     - 127.0.0.1:3001:3000
  #   command: npm start

  # db:
  #   image: postgres:14.4-alpine
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: $POSTGRES_DB
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  #   container_name: pg_c
