version: '3.6'

services:
  server:
    image: node:16.16.0-alpine
    volumes:
      - ./backend:/usr/local/backend
    working_dir: /usr/local/backend
    env_file: .env
    ports:
      - '127.0.0.1:3001:3001'
    command: npm run dev
    container_name: server_c

  client:
    image: node:16.16.0-alpine
    volumes:
      - ./frontend:/usr/local/client
    working_dir: /usr/local/client
    # environment:
    #   - REACT_API_URL=http://server:3000
    ports:
      - 127.0.0.1:3000:3000
    command: npm start
    container_name: client_c

  db:
    image: postgres:14.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    container_name: pg_c

  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_NAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PWD
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
      - mongo-data:/data/db
    working_dir: /usr/local/sampleCollections
    container_name: mongo_c

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
  #     - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
  #   ports:
  #     - '5050:80'
  #   restart: always
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   container_name: pga_c

volumes:
  mongo-data: {}
  db-data: {}
  pgadmin: {}
