POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "2032@test.com",
  "password": "OKOKOKO2K",
  "firstName": "firstname"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "2032@test.com",
  "password": "OKOKOKO2K",
  "firstName": "firstname"
}