POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "email": "aaaaa@test.com",
  "password": "OKOKOKO2K",
  "firstName": "firstnameTEST",
  "role": "usaer"
}

###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "aaaaa@test.com",
  "password": "OKOKOKO2K",
  "firstName": "firstnameTEST"
}