POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "email": "qqqa@test.com",
  "password": "OKOKOKO2K",
  "firstName": "firstnameTEST"
}

###
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "qqqa@test.com",
  "password": "OKOKOKO2K",
  "firstName": "firstnameTEST"
}