# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiZmlyc3RuYW1lIiwiaWF0IjoxNjU3MTExNzI1LCJleHAiOjE2ODg2NjkzMjV9.XI3htgOYZC-M2h4skEY-NNSInKxFICbQhyzAY-TeV9I
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiZmlyc3RuYW1lIiwiaWF0IjoxNjU3MTExNzI1LCJleHAiOjE2ODg2NjkzMjV9.XI3htgOYZC-M2h4skEY-NNSInKxFICbQhyzAY-TeV9I

###
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiZmlyc3RuYW1lIiwiaWF0IjoxNjU3MTExNzI1LCJleHAiOjE2ODg2NjkzMjV9.XI3htgOYZC-M2h4skEY-NNSInKxFICbQhyzAY-TeV9I

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "firstName 1",
  "password": "OKOdewKOKOK"
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiZmlyc3RuYW1lIiwiaWF0IjoxNjU3MTExNzI1LCJleHAiOjE2ODg2NjkzMjV9.XI3htgOYZC-M2h4skEY-NNSInKxFICbQhyzAY-TeV9I

{
  "firstName": "updated",
  "lastName": "updated lastName",
  "password": "asdasdasd"
}

###
DELETE http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

