GET http://localhost:3000/users

###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "firstName 1",
  "password": "OKOdewKOKOK"
}

###
PUT http://localhost:3000/users/3
Content-Type: application/json

{
  "firstName": "updated",
  "lastName": "updated lastName",
  "password": "asdasdasd"
}

###
DELETE http://localhost:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "203@test.com",
    "password": "OKOKOKOK",
    "firstName": "The request has succeeded."
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "203@test.com",
    "password": "OKOKOKOK"
}